---
apiVersion: v1
kind: ConfigMap
metadata:
  name: npass
data:
  npass.json: |
    {
      "currentContext": "default"
      , "contexts": [
        {
          "name": "default"
          , "store": "postgres://user:password@host:port/database"
          , "api": {
            "listen": ":80"
            , "authToken": "aegoh1gi0RooheiRaeChesh0maef8pheesoosh3lohmaewaRikahkeishohX9noh"
          }
        }
      ]
    }