---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: npass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npass
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: npass
    spec:
      containers:
        - env:
          image: nwehr/npass
          imagePullPolicy: Always
          name: npass
          volumeMounts:
          - name: npass-vol
            mountPath: /root/.npass
      volumes:
      - name: npass-vol
        configMap:
          name: npass
  
---
kind: Service
apiVersion: v1
metadata:
  name: npass-service
spec:
  selector:
    app: npass
  ports:
    - port: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wan
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: npass.errorcode.io
    http:
      paths:
      - path: /wehrholdings/(.*)
        pathType: Prefix
        backend:
          service:
            name: npass-service
            port:
              number: 80
        